FROM python:3.9.6-alpine3.14 as TestBench
ENV http_proxy ${http_proxy}
ENV https_proxy ${https_proxy}

COPY ./requirements_test.txt /tmp/
RUN pip install -r /tmp/requirements_test.txt

FROM TestBench
COPY ./ /opt/app/
WORKDIR /opt/app/

RUN pytest --cov=src